### ISSUE TITLE
[New Package]: XunLei.xunlei (Thunder.Thunder)

### ISSUE THREAD

**Issue by Meng5in** [vedantmgoyal2009/vedantmgoyal2009#1198]
### List the PackageIdentifier of the package to be added to automation

XunLei.xunlei

### Details about the application

https://down.sandai.net/thunder11/XunLeiSetup11.3.7.1880.exe

**Comment by SpecterShell** [comment]
I got one but it is 404. 🤔
http://static-xl.a.88cdn.com/json/thunderx_bind_config_100001.json

**Comment by vedantmgoyal9** [comment]
I got one - https://static-xl9-ssl.xunlei.com/json/xl11_official_page.json
