### ISSUE TITLE
[New Package]: Nutstore.Nutstore

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal2009/vedantmgoyal2009#133]
### List the PackageIdentifier of the package to be added to automation

Nutstore.Nutstore

### Details about the application

```powershell
(Invoke-WebRequest -Uri 'https://app.jianguoyun.com/static/exe/latestVersion' -UserAgent 'NutstoreApp-6.2.4').Content | ConvertFrom-Json | Where-Object {$_.OS -eq 'win-wpf-client'}
```

Use `stVer` as PackageVersion and fill in
`https://www.jianguoyun.com/static/exe/installer/$ver/NutstoreInstaller_$ver.exe`
to get the InstallerUrl.
e.g. https://www.jianguoyun.com/static/exe/installer/5.2.4/NutstoreInstaller_5.2.4.exe

**Comment by vedantmgoyal2009** [comment]
Is UserAgent necessary? I can access it normally.

![image](https://user-images.githubusercontent.com/83997633/140483490-8799205d-eadf-4c86-b414-20865badb0a8.png)

**Comment by SpecterShell** [comment]
![image](https://user-images.githubusercontent.com/56779163/140497412-4a0a7d4e-0e3b-4c3a-8eb4-8ac5d4bc4e64.png)

**Comment by SpecterShell** [comment]
`"pkgid": "nuttyartist.notes",`
It seems that the `pkgid` in `/packages/n/nutstore.nutstore.json` is wrong.

**Comment by vedantmgoyal2009** [comment]
I've fixed it. Thanks for catching that.

**Comment by SpecterShell** [comment]
The source URL can be changed to https://www.jianguoyun.com/static/exe/latestVersion which doesn't need custom useragent.

For x64 and x86 installer:
PackageVersion: `($result | Where-Object {$_.OS -eq 'win-wpf-client'}).exVer`
InstallerUrl: `https://pkg-cdn.jianguoyun.com/static/exe/installer/$ver/NutstoreWindowsWPF_Full_$ver.exe`

For arm64 installer:
PackageVersion: `($result | Where-Object {$_.OS -eq 'win-wpf-client-arm64'}).exVer` or use the same version as x86 one.
InstallerUrl: `https://pkg-cdn.jianguoyun.com/static/exe/installer/$ver/NutstoreWindowsWPF_Full_$ver_ARM64.exe`
