### ISSUE TITLE
[New Package]: FengHe.FocusNote

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal2009/vedantmgoyal2009#162]
### List the PackageIdentifier of the package to be added to automation

FengHe.FocusNote

### Details about the application

```powershell
$body = @{
    platform = '0'
    prodNo = '0'
}
Invoke-RestMethod -Uri 'https://focusnote.com.cn/admin/version/listNew' -Method Post -Body $body
```
InstallerUrl: `$result.data[0].downloadUrl` or `$result.data.downloadUrl` (`$result.data` is an array and PowerShell automatically takes the first one)
PackageVersion: From InstallerUrl
e.g. https://download.kirakuapp.com/FN_PC/Focus%20Note%20Setup%202.12.6-661.exe -> `2.12.6-661`

**Comment by vedantmgoyal2009** [comment]
@SpecterShell Any way to post body as a string rather than a hashtable?

**Comment by SpecterShell** [comment]
Invoke-RestMethod -Uri 'https://focusnote.com.cn/admin/version/listNew' -Method Post -Body 'platform=0&prodNo=0'

**Comment by vedantmgoyal2009** [comment]
Thanks! Actually, I needed it because in the new automation, data types of parameters are fixed.

**Comment by SpecterShell** [comment]
They have changed the source to a new URL in the latest version:
https://fn.kirakuapp.com/admin/version/listNew
