### ISSUE TITLE
[New Package]: DriversCloud.com

### ISSUE THREAD

**Issue by laedit** [vedantmgoyal2009/vedantmgoyal2009#168]
### List the PackageIdentifier of the package to be added to automation

Cybelsoft.DriversCloud

### Details about the application

The source for the versions of this software are here: https://www.driverscloud.com/plugins/
It is a directory listing, I don't know if it can be handled.
It is possible to get the last version through this powershell lines:
- for x86:
``` pwsh
$r=iwr https://www.driverscloud.com/plugins/ -UseBasicParsing 
$installerUrl = "https://www.driverscloud.com/plugins$($r.Links |?{$_.href -match "DriversCloud_(\d{2,}.*)\.exe$"} | select -ExpandProperty HREF | Sort-Object | select -last 1)"
$version = $Matches[1]
```
- for x64:
``` pwsh
$r=iwr https://www.driverscloud.com/plugins/ -UseBasicParsing 
$installerUrl = "https://www.driverscloud.com/plugins$($r.Links |?{$_.href -match "DriversCloudx64_(\d{2,}.*)\.exe$"} | select -ExpandProperty HREF | Sort-Object | select -last 1)"
$version = $Matches[1]
```
Let me know if you need more info, thanks for this awesome automation!
Edit: added version in scripts.

**Comment by vedantmgoyal2009** [comment]
@all-contributors please add @laedit for ideas

**Comment by vedantmgoyal9** [comment]
Hello, I think the website has changed now. Could please find any other source?

**Comment by laedit** [comment]
Thanks for letting me know!

Here is the new version:
x86:
``` pwsh
$r=iwr https://www.driverscloud.com/en/my-drivers -UseBasicParsing 
$r.Content -match 'class="versionapp.*?([0-9]{1,2}\.[0-9]{1,2}.[0-9]{1,2}.[0-9]{1,2})\<'
$version = $Matches[1]
$installerUrl = "https://mcdrivers.driverscloud.com/applis/DriversCloud_$($Matches[1]).exe"
```

x64:
``` pwsh
$r=iwr https://www.driverscloud.com/en/my-drivers -UseBasicParsing 
$r.Content -match 'class="versionapp.*?([0-9]{1,2}\.[0-9]{1,2}.[0-9]{1,2}.[0-9]{1,2})\<'
$version = $Matches[1]
$installerUrl = "https://mcdrivers.driverscloud.com/applis/DriversCloudx64_$($Matches[1]).exe"
```

**Comment by SpecterShell** [comment]
Thanks to their online installer, this can be much easier:
https://www.driverscloud.com/update.xml
