### ISSUE TITLE
[New Package]: Microsoft.OneDrive.*

### ISSUE THREAD

**Issue by vedantmgoyal2009** [vedantmgoyal2009/vedantmgoyal2009#193]
### List the PackageIdentifier of the package to be added to automation

Microsoft.OneDrive.*

### Details about the application

@ItzLevvie Do you know any API for OneDrive?

**Comment by vedantmgoyal2009** [comment]
So, I found some sources from Evergreen.

`Production`: https://g.live.com/1rewlive5skydrive/OneDriveProduction
`Enterprise`: https://g.live.com/1rewlive5skydrive/OneDriveEnterprise
`Insiders`: https://g.live.com/1rewlive5skydrive/OneDriveInsider
`Internal`: https://g.live.com/1rewlive5skydrive/OneDriveInternal

I think I have direct sources for `Production`, `Enterprise` and `Insiders` channels. Can you tell me how to differentiate b/w `InternalSlow` and `InternalFast` channels? Or, maybe we can purge the separate packages and start a new package with only `Internal` builds?

Also, I would like to put the same thing as I did for Teams (CD and Exploration), only the last X versions for `Insiders` and `Internal` builds of OneDrive?

**Comment by ItzLevvie** [comment]
Looks like Microsoft has changed the links a bit. I logged into my corporate account into a virtual machine and here are the new links:

`Production`: https://g.live.com/1rewlive5skydrive/OneDriveProductionV2
`Enterprise`: https://g.live.com/1rewlive5skydrive/OneDriveEnterpriseV2
`Insiders`: https://g.live.com/1rewlive5skydrive/OneDriveInsiderV2
`Internal Fast`: https://g.live.com/1rewlive5skydrive/MsitFastV2
`Internal Slow`: https://g.live.com/1rewlive5skydrive/MsitSlowV2

MSIT = Our IT Department (known as Microsoft IT / CSEO)

**Comment by vedantmgoyal2009** [comment]
Thanks @ItzLevvie for your help.

**Comment by vedantmgoyal2009** [comment]
@allcontributors please add @ItzLevvie for ideas

**Comment by vedantmgoyal2009** [comment]
@allcontributors please add @ItzLevvie for ideas

**Comment by vedantmgoyal2009** [comment]
@ItzLevvie I think there's a bug in the API since it is returning two versions and I am not sure which one is to be selected. 

Affected channels: `Production`, `Insiders`, `Internal Slow`.

The below screenshot is from the `Production` ring.
![image](https://user-images.githubusercontent.com/83997633/150209928-84926fdd-28c5-4189-8607-8591d8daa1f0.png)

**Comment by ItzLevvie** [comment]
> I am not sure which one is to be selected.

Choose the second one.

**Comment by vedantmgoyal2009** [comment]
Ohk, thanks.

**Comment by vedantmgoyal9** [comment]
Fixed in commit a79ab0101dd567b8ca53553fbc3eddc6f667386d.
