### ISSUE TITLE
[New Package]: RStudio.RStudio.OpenSource

### ISSUE THREAD

**Issue by eitsupi** [vedantmgoyal2009/vedantmgoyal2009#209]
### List the PackageIdentifier of the package to be added to automation

RStudio.RStudio.OpenSource

### Details about the application

We can get RStudio Desktop for Windows from this page. https://www.rstudio.com/products/rstudio/download/#download
Installer URL: https://download1.rstudio.org/desktop/windows/RStudio-2021.09.1-372.exe

The released version is linked to [the tag on the GitHub repository](https://github.com/rstudio/rstudio/tags) (e.g. `v2021.09.1+372`), but there may be a small time lag between when the tag is published and when the installer URL becomes active.

`+` in the version has been replaced by `-` in the installer URL.

**Comment by vedantmgoyal2009** [comment]
@allcontributors please add @eitsupi for ideas
