### ISSUE TITLE
[New Package]: Citrix Workspace

### ISSUE THREAD

**Issue by felipecrs** [vedantmgoyal2009/vedantmgoyal2009#246]
### List the PackageIdentifier of the package to be added to automation

Citrix.Workspace

### Details about the application

Citrix Workspace is an application used for remote access in many companies. As the package already exists in WinGet repo (but it's outdated), all the data which is there can be reused like description.

https://github.com/microsoft/winget-pkgs/tree/master/manifests/c/Citrix/Workspace/21.9.1.4048

New version numbers can be found here: https://www.citrix.com/pt-br/downloads/workspace-app/windows/workspace-app-for-windows-latest.html

Installer URL seem to be available using this pattern:

![image](https://user-images.githubusercontent.com/29582865/148777416-434f1da6-caa4-4fe4-b90f-27652cf27783.png)

https://downloadplugins.citrix.com/ReceiverUpdates/Prod/Receiver/Win/CitrixWorkspaceApp21.12.1.4030.exe

Where 21.12.1.4030 is the version.

**Comment by vedantmgoyal2009** [comment]
I guess I should switch it to webpage scraping or find the new URL where latest versions are posted.

**Comment by vedantmgoyal2009** [comment]
@allcontributors please add @felipecrs for ideas

**Comment by vedantmgoyal2009** [comment]
@allcontributors please add @felipecrs for bugs

**Comment by felipecrs** [comment]
Thanks a lot for the consideration, @vedantmgoyal2009!

By the way, up to now the XML file still wasn't updated. I think we can indeed consider that it's not the best place to look for updates any longer.

Meanwhile, the package got upgraded in WinGet (manually, I guess): https://github.com/microsoft/winget-pkgs/pull/40503

But this is purely informative, do not consider this comment as a reason to rush the fix or implementation. Perhaps when Citrix releases the next version, I can give it a chance to send a PR.

**Comment by vedantmgoyal9** [comment]
@felipecrs I have switched to webpage scraping. Now, as a new version is released, automatic PR should be created. Sorry for the delay.

**Comment by felipecrs** [comment]
That's very nice!

And don't say sorry, I that thank you!
