### ISSUE TITLE
[New Package]: SWI-Prolog.SWI-Prolog

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal2009/vedantmgoyal2009#247]
### List the PackageIdentifier of the package to be added to automation

SWI-Prolog.SWI-Prolog

### Details about the application

InstallerUrl for x64:
```PowerShell
(Invoke-WebRequest -Uri 'https://www.swi-prolog.org/download/stable/bin/swipl-latest.x64.exe' -Method Head).BaseResponse.RequestMessage.RequestUri.AbsoluteUri
```

InstallerUrl for x86:
```PowerShell
(Invoke-WebRequest -Uri 'https://www.swi-prolog.org/download/stable/bin/swipl-latest.x86.exe' -Method Head).BaseResponse.RequestMessage.RequestUri.AbsoluteUri
```

PackageVersion: From InstallerUrl

**Comment by vedantmgoyal9** [comment]
Can't we use any one source and replace `x64` with `x86`? Just wanted to know your opinion🤔

**Comment by SpecterShell** [comment]
https://www.swi-prolog.org/download/stable/bin/
IMO you can do this safely.
