### ISSUE TITLE
[New Package]: Yemiao.Xtranslator

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal2009/vedantmgoyal2009#249]
### List the PackageIdentifier of the package to be added to automation

Yemiao.Xtranslator

### Details about the application

PackageVersion: https://free.zhiyunwenxian.cn/xtrans/UpdateData.txt
InstallerUrl: https://free.zhiyunwenxian.cn/xtrans/UpdateURL.txt

**Comment by vedantmgoyal9** [comment]
![image](https://user-images.githubusercontent.com/83997633/157092858-75b3ba53-270d-4f77-9277-c247fec8aa0e.png)

Are these `ReleaseNotes`?

**Comment by SpecterShell** [comment]
The first line is used as version number, and the remaining is the text that is displayed when new version is available, which contains ReleaseNotes.
![image](https://user-images.githubusercontent.com/56779163/157162538-8ffca316-b5d2-4df5-9ece-77ecb46d63f4.png)
