### ISSUE TITLE
[New Package]: Neux.OneMark

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal2009/vedantmgoyal2009#264]
### List the PackageIdentifier of the package to be added to automation

Neux.OneMark

### Details about the application

https://onemark.neuxlab.cn/updates/latest.x64.xml
https://onemark.neuxlab.cn/updates/latest.xml

InstallerUrl: `$result.item.url`
You can remove `?v=\d{8}` at the end of the urls if you like.

PackageVersion: From msi package
https://stackoverflow.com/questions/8743122/how-do-i-find-the-msi-product-version-number-using-powershell

Ongoing pull request:
https://github.com/microsoft/winget-pkgs/pull/41804

**Comment by vedantmgoyal9** [comment]
Can't we use any one source and replace `x64` with `null`? Will it be good instead of fetching two sources?

**Comment by SpecterShell** [comment]
Sorry for late reply. You can do so if you think it is more feasible. 😺

**Comment by vedantmgoyal9** [comment]
Sources are dead. 
![image](https://user-images.githubusercontent.com/83997633/186104335-be54ec4d-a6fa-401a-b4b4-1cba8be332cd.png)

**Comment by SpecterShell** [comment]
Accessible here. 🤔
