### ISSUE TITLE
[New Package]: Youdao.youdaodict

### ISSUE THREAD

**Issue by lychichem** [vedantmgoyal2009/vedantmgoyal2009#265]
### List the PackageIdentifier of the package to be added to automation

Youdao.YoudaoDict

### Details about the application

PackageName: 网易有道词典
Moniker: youdaodict
Publisher: 网易公司
Author: Youdao
License: YoudaoDict License
ShortDescription: Youdao Dictionary has typical acoustic translation, smart screen word identification, real-time synchronization with network up-to-date vocabulary, and other word look-up features.
Tags: dictionary, dict, cloud, online
InstallerType: maybe `Nullsoft`, but I use `exe` in manifests now.
Architecture: x86
InstallerUrl: a stale url is `http://cidian.youdao.com/download/YoudaoDict.exe`, and it will redirect to `http://download.ydstatic.cn/cidian/static/<first two part of version number>/<release date>/YoudaoDictSetup.exe`

You can download a new version now. It's `8.10.5.0`.

**Comment by SpecterShell** [comment]
http://cidian.youdao.com/apps/update5/fdictupdate.xml?ver=1400
`1400` in the URL and all `\d{4}` numbers in the source seem to be a kind of build number and I have no idea where to get them anywhere else.

BTW, how about moving `Youdao.YoudaoDict` to `Netease.YoudaoDict`?

**Comment by lychichem** [comment]
> http://cidian.youdao.com/apps/update5/fdictupdate.xml?ver=1400
> `1400` in the URL and all `\d{4}` numbers in the source seem to be a kind of build number and I have no idea where to get them anywhere else.
> 
> BTW, how about moving `Youdao.YoudaoDict` to `Netease.YoudaoDict`?

1. Can we use GET to obtain the real URL for the installer from stale URL?
2. Agree.

**Comment by SpecterShell** [comment]
```PowerShell
$response = Invoke-WebRequest -Uri 'http://cidian.youdao.com/download/YoudaoDict.exe' -Method Head
$response.BaseResponse.RequestMessage.RequestUri.AbsoluteUri
```
`HEAD` is better since it can let server return response without body.

**Comment by lychichem** [comment]
> ```powershell
> $response = Invoke-WebRequest -Uri 'http://cidian.youdao.com/download/YoudaoDict.exe' -Method Head
> $response.BaseResponse.RequestMessage.RequestUri.AbsoluteUri
> ```
> 
> `HEAD` is better since it can let server return response without body.

Then the problem is how to get the last two part of version number.

**Comment by vedantmgoyal2009** [comment]
@allcontributors please add @lychichem for ideas

**Comment by lychichem** [comment]
> > ```powershell
> > $response = Invoke-WebRequest -Uri 'http://cidian.youdao.com/download/YoudaoDict.exe' -Method Head
> > $response.BaseResponse.RequestMessage.RequestUri.AbsoluteUri
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `HEAD` is better since it can let server return response without body.
> 
> Then the problem is how to get the last two part of version number.

![image](https://user-images.githubusercontent.com/9316590/153194144-37f2f0b7-5d56-47fb-ba78-6fc4838de5a4.png)
@vedantmgoyal2009 Okay, we can get full version number of the installer from its property. So could you please update the manifest automatically?

**Comment by vedantmgoyal9** [comment]
Sorry for the delay, I have added the package now🙂
