### ISSUE TITLE
[New Package]: XMind.XMind

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal2009/vedantmgoyal2009#270]
### List the PackageIdentifier of the package to be added to automation

XMind.XMind

### Details about the application

https://www.xmind.net/xmind/update/latest-win64.yml
https://www.xmind.net/xmind/update/latest-win32.yml

Ongoing pull requests:
https://github.com/microsoft/winget-pkgs/pull/42097
https://github.com/microsoft/winget-pkgs/pull/42095
https://github.com/microsoft/winget-pkgs/pull/42093
https://github.com/microsoft/winget-pkgs/pull/42094
https://github.com/microsoft/winget-pkgs/pull/42088

**Comment by vedantmgoyal2009** [comment]
@SpecterShell One PR will work. I asked because it is hard to navigate to the manifest and check if the data fetched by the automation is correct or not.

**Comment by SpecterShell** [comment]
It seems that they have droped x86 support in the latest version. So only one installer is needed now.

https://github.com/microsoft/winget-pkgs/pull/56503
