### ISSUE TITLE
[New Package]: FileZilla Client

### ISSUE THREAD

**Issue by vedantmgoyal2009** [vedantmgoyal2009/vedantmgoyal2009#33]
### List the PackageIdentifier of the package to be added to automation

TimKosse.FileZilla.Client ~TimKosse.FileZillaClient~

### Details about the application

From Evergreen: 
https://github.com/aaronparker/evergreen/blob/main/Evergreen/Manifests/FileZilla.json

**Comment by vedantmgoyal9** [comment]
Removed from WinGet.
- FileZilla ticket: https://trac.filezilla-project.org/ticket/12768
- GitHub: https://github.com/microsoft/winget-pkgs/issues/78578#issuecomment-1238126217
- (For reference) Scoop: https://github.com/ScoopInstaller/Extras/issues/9179#issue-1363052014
