### ISSUE TITLE
[New Package]: Octopus Deploy Tentacle

### ISSUE THREAD

**Issue by vedantmgoyal2009** [vedantmgoyal2009/vedantmgoyal2009#42]
### List the PackageIdentifier of the package to be added to automation

OctopusDeploy.Tentacle

**Comment by vedantmgoyal2009** [comment]
@jedieaston Now has it been fixed?

**Comment by jedieaston** [comment]
It doesn't look like it:

![image](https://user-images.githubusercontent.com/21368066/147250652-bb65bed1-9aa6-4323-b7f6-25f9b576c26a.png)
