### ISSUE TITLE
[New Package]: Glodon.CADReaderInternational

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal2009/vedantmgoyal2009#65]
### List the PackageIdentifier of the package to be added to automation

Glodon.CADReaderInternational

### Details about the application

API:
`https://cadreader.glodon.com/query/update/cadpc?clientVersion=$($version)&cadpcClientBits=32`
e.g. https://cadreader.glodon.com/query/update/cadpc?clientVersion=3.4.3.12&cadpcClientBits=32

`$result.data.url` InstallerUrl
`$result.data.version` PackageVersion

**Comment by SpecterShell** [comment]
`Glodon.CADReaderInternational` is moving to `Glodon.CADReader`

**Comment by vedantmgoyal9** [comment]
Well, you also should also be able to move the package in the automation.
- the field in the JSON should be case-sensitive,
- the JSON filename should be all in lowercase.

I guess you can do this using the GitHub web editor. The reason I'm saying this that I have my exams this and the upcoming week. I only approve the PRs here and open some auto-generated PRs at the community repository. I have limited my time on GitHub for just ½ hour till 11th of March.
