### ISSUE TITLE
[Feature/Idea]: New Package Script

### ISSUE THREAD

**Issue by Trenly** [vedantmgoyal2009/vedantmgoyal2009#93]
### What would you like to see changed/added?

I would suggest there be a script that runs any time a new package is added to automation. It can be triggered based on when a new .json file is created in the /packages folder

This script would fetch ALL the previous releases and attempt to add them to winget-pkgs. That way, as many versions of an application are available as possible

**Comment by vedantmgoyal2009** [comment]
I think it will work only for non-GitHub packages.

**Comment by vedantmgoyal2009** [comment]
@jedieaston Last 15-20 versions would be fine?

**Comment by jedieaston** [comment]
That's __probably__ fine, although since we're supposed to be checking ARP data for PRs we approve (especially of new apps), that still seems like a lot. 

If a dev changes their publisher name halfway through, do you have any ideas on how to validate that on your end? Eventually the pipelines will have a way to do it themselves, but I think that isn't happening until post 1.1.

**Comment by jedieaston** [comment]
> I am also thinking of making a script to validate all packages (including all versions of that package) using Windows Sandbox. 

I've done something like this before, using some modifications to Levvie's moderation script. Haven't been using it because I'm still kind of against doing sweeping ARP changes right now because we'll have to redo all of that work in schema 1.1, but I think just verifying it for now would be a good idea.

**Comment by vedantmgoyal2009** [comment]
@jedieaston I've implemented a check for ARP metadata and you can see the logs of this [workflow run](https://github.com/vedantmgoyal2009/winget-pkgs-automation/runs/3936242231?check_suite_focus=true). I only have to make them print better in the logs. They look too dirty as of now.

**Comment by Trenly** [comment]
> You're right. I first created a development branch, made and tested all the changes locally, and finally at last merged them (#108).

I see. I’ll have to look more after work today

**Comment by jedieaston** [comment]
If it helps, here's how I do it (well, wrapped up cleanly): https://gist.github.com/jedieaston/edd6f1983108c1c220bbf6d9d18d3c4c

**Comment by vedantmgoyal2009** [comment]
@jedieaston can you make your function that it can stop itself if the installation doesn't get completed within a certain period of time?

**Comment by jedieaston** [comment]
This works for me:

```
$init = {
function Get-ARPTable {
    $registry_paths = @('HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*','HKLM:\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*', 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*', 'HKCU:\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*')
    return Get-ItemProperty $registry_paths -ErrorAction SilentlyContinue |
         Select-Object DisplayName, DisplayVersion, Publisher, @{N='ProductCode'; E={$_.PSChildName}}|
         Where-Object {$null -ne $_.DisplayName } |
         Where-Object {$null -ne $_.DisplayVersion } |
         Where-Object {$null -ne $_.Publisher }
        }


# See how the ARP table changes before and after a ScriptBlock.
function Get-ARPTableDifference {
    Param (
        [Parameter(Mandatory=$true)]
        [scriptblock]
        $ScriptToRun
    )
    $originalArp = Get-ARPTable
    $ScriptToRun | Invoke-Expression 
    $currentArp = Get-ARPTable
    return (Compare-Object $currentArp $originalArp).InputObject
}}
$Job = Start-Job -InitializationScript $init { 
Get-ARPTableDifference { winget install Microsoft.Teams; } 
} | Wait-Job -Timeout 3
$Job = Get-Job | ? {$_.State -eq 'Running'} | Stop-Job -PassThru
```

(with the last line killing any jobs that are still running). 

If you want stdout from `winget`, you might be able to use the `.Output` member variable of the job. I'm not 100% sure how this works, but [this](https://stackoverflow.com/a/60180019) looks promising.

**Comment by vedantmgoyal9** [comment]
I don't know if this is still relevant since we have recently removed old versions of some packages from winget-pkgs repository.
